CREATE TABLE IF NOT EXISTS "keys" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"key" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "data" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"user_id" INTEGER NOT NULL,
	"title" TEXT NOT NULL,
	"category" TEXT NOT NULL,
	"content" TEXT,
	PRIMARY KEY("id"),
	FOREIGN KEY ("user_id") REFERENCES "keys"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
